#!/bin/bash

# This alternate file will compile jcdriver and jcmapper.
# Please edit line 31 to change the `/home/noah` to your home directory, and change the..
# .. `/home/noah/JoyCons` to the location where you would like the files to be saved to.

#sudo apt-get install -y binutils bison libudev-dev screen
# install gvm
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source /home/noah/.gvm/scripts/gvm

# install go
gvm install go1.4 --binary
gvm use go1.4
export GOROOT_BOOTSTRAP=$GOROOT
gvm install go1.8 --binary
gvm use go1.8 --default

mkdir -p ~/go/src/github.com/riking
#cat << "EOF" >> ~/.profile
#export PATH=$PATH:/usr/local/go/bin
#export GOPATH=$HOME/go
#EOF
source ~/.profile

# cat /proc/bus/input/devices

cd ~/go/src/github.com/riking
git clone https://github.com/riking/joycon.git
cd joycon
make all
cp /home/noah/go/bin/jcdriver /home/noah/go/src/github.com/riking/joycon/jcmapper /home/noah/JoyCons
#cd prog4
#go get ./...
cd ..
#cd ..
rm -rf joycon
cd
